CREATE TABLE IF NOT EXISTS financial_data (
  "FINANCIAL_TYPE" TEXT,
  "SYMBOL" TEXT,
  "SECURITY_NAME" TEXT,
  "SEDOL" TEXT,
  "ISIN" TEXT,
  "PRICE" REAL,
  "QUANTITY" REAL,
  "REALISED_P_L" REAL,
  "MARKET_VALUE" REAL,
  "FUND_NAME" TEXT,
  "Month" TEXT
);
